Javascript/javascript2/week3
aijazraja/hyf-homework pull request #10
Opened 2020-12-11 01:36 UTC by aijazraja

2020-12-11 11:47 UTC, JyothiNandyala commented on javascript/javascript2/week3/functions.js
> +var funcs = [
Please try avoid the var .here instead of var use let.

2020-12-11 11:49 UTC, JyothiNandyala commented on javascript/javascript2/week3/functions.js
> +
Remove the unwanted/commented code before pushing into github.

2020-12-11 12:19 UTC, JyothiNandyala commented on javascript/javascript2/week3/presser.js
> +
if you want to add confetti to your code first you can copy the script link from the homework link and paste it into before calling the main js file.and also you can add the javascript code into after the below line.
 document.getElementById('winner').innerHTML='L is winner <br> Score<br>'+score;and also  
document.getElementById('winner').innerHTML='S is winner <br> Score<br>'+score; and here also the same  with different canvas id.

2020-12-11 12:21 UTC, JyothiNandyala commented on javascript/javascript2/week3/warmup.js
> +
You did a good job.

2020-12-11 12:22 UTC, JyothiNandyala commented on javascript/javascript2/week3/presser.js
> +
i have seen your output you did a good job,if you add conffeti its very good for  looking.

2020-12-11 12:24 UTC, JyothiNandyala requested changes
Its good  work.if you not understand my comments please let me know.

2020-12-11 17:40 UTC, qamarfj reviewed
Good job.

2021-01-03 23:32 UTC, NayanaKamtekar approved these changes
Good work!
Your fastest presser game works well for values 1- 9 sec. but if we set 10 or more than 10 sec then game overs in 1 sec. Try to fix it.

In this PR I can see many files from JavaScript 1 homework and merging this PR will add those file changes. Try to avoid that. Will make it also much more easier to review the homework.

2021-01-03 23:32 UTC, NayanaKamtekar commented on javascript/javascript2/week3/warmup.js
> +
Good !

2021-01-04 04:30 UTC, aijazraja reviewed
> Good work!
> Your fastest presser game works well for values 1- 9 sec. but if we set 10 or more than 10 sec then game overs in 1 sec. Try to fix it.
it's fixed now it's working for more than 9 seconds

2021-01-04 04:30 UTC, aijazraja commented on javascript/javascript2/week3/presser.js
> +
Thanks for the reviews Jyothi
I have implemented all changes you suggest to me.
this confetti part I have implemented on my result part now. So the result part will have confetti now :)

2021-01-04 04:35 UTC, merged