Database Week2 is ready for comments
aijazraja/hyf-homework pull request #15
Opened 2021-01-22 04:07 UTC by aijazraja

2021-01-23 16:56 UTC, aina21 requested changes
good job

2021-01-23 16:56 UTC, aina21 commented on databases/week2/week2_part3.sql
> +/*
you should use data for lesson2 for this part.
https://github.com/HackYourFuture-CPH/databases/blob/master/lesson2/lesson2-data.sql

2021-01-23 17:00 UTC, pritalpatel commented on databases/week2/week2_part1.sql
> +values('meeeting','meeting with comapany owner','2021-01-15 task','2021-01-19 06:54:16','2021-02-18 06:54:16',2,3);
```suggestion
values('meeeting','meeting with comapany owner','**2021-01-15 task**','2021-01-19 06:54:16','2021-02-18 06:54:16',2,3);
```
I think 'created' as a DATE datatype, Its not allow to insert string.

2021-01-23 17:00 UTC, pritalpatel commented on databases/week2/week2_part2.sql
> +on Student(name);
Give a proper name when create a index for ex. index_student
```suggestion
create index index_student
on Student(id);
```
index on a VARCHAR column will boost query performance
It's make more sense to find a INT column to create INDEX on it.

2021-01-23 17:00 UTC, pritalpatel commented on databases/week2/week2_part4.sql
> +  id INT NOT NULL AUTO_INCREMENT,
```suggestion
  id INT(5) NOT NULL AUTO_INCREMENT,
```
Define a specific range for the INT(n) data type.
It's consider on the performance, compression and indexes

2021-01-23 17:11 UTC, aina21 commented on databases/week2/week2_part1.sql
> +values('meeeting','meeting with comapany owner','2021-01-15 task','2021-01-19 06:54:16','2021-02-18 06:54:16',2,3);
you can use NOW(),
https://www.w3schools.com/sql/func_mysql_now.asp

2021-02-18 18:05 UTC, aijazraja commented on databases/week2/week2_part4.sql
> +  id INT NOT NULL AUTO_INCREMENT,
Hi pritalpatel
Thanks for your feedback
i have fixed all of your proposed comments

2021-02-18 18:06 UTC, merged